development:
  dialect: postgres
  datasource: user=${DB_USER} password=${DB_PASSWORD} host=${DB_HOST} port=${DB_PORT} dbname=${DB_NAME} sslmode=${DB_SSLMODE}
  dir: migrations
  table: gorp_migrations

production:
  dialect: postgres
  datasource: user=${DB_USER} password=${DB_PASSWORD} host=${DB_HOST} port=${DB_PORT} dbname=${DB_NAME} sslmode=${DB_SSLMODE}
  dir: migrations
  table: gorp_migrations